### ISSUE TITLE
Repo URI outdated?

### ISSUE THREAD

**Issue by olifre** [italiangrid/storm#90]
The file `http://italiangrid.github.io/storm/repo/storm_sl6.repo` lists
`http://ci-01.cnaf.infn.it/download/storm/emi3/sl6/x86_64` which gives 404. 

That's still mentioned in the documentation. 

What's the current repository URI?

**Comment by enricovianello** [comment]
Hi @olifre,

thanks for reporting! We're fixing it.
As soon as it will be back online I'll report here.

**Comment by enricovianello** [comment]
http://ci-01.cnaf.infn.it/download/storm/emi3/sl6/x86_64
is online.

**Comment by olifre** [comment]
@enricovianello Thanks a lot for the quick response! I can confirm it's working now 👍
